//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinacija_Koristi_Luku
    {
        public int Destinacija_brDestinacije { get; set; }
        public int Luka_idLuke { get; set; }
    
        public virtual Luka Luka { get; set; }
    }
}
