//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int brKarte { get; set; }
        public decimal cena { get; set; }
        public string klasa { get; set; }
        public int jmbg { get; set; }
        public Nullable<int> brAgencije { get; set; }
        public int brPlovidbe { get; set; }
        public System.DateTime datum { get; set; }
        public int idBroda { get; set; }
    
        public virtual Agencija Agencija { get; set; }
        public virtual Putnik Putnik { get; set; }
        public virtual Plovidba Plovidba { get; set; }
        public virtual Putnicki Putnicki { get; set; }
    }
}
