//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseTracker.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luka()
        {
            this.Destinacija_Koristi_Luku = new HashSet<Destinacija_Koristi_Luku>();
            this.Plovidbas = new HashSet<Plovidba>();
        }
    
        public int idLuke { get; set; }
        public int brDokova { get; set; }
        public string naziv { get; set; }
        public string mesto { get; set; }
        public string drzava { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destinacija_Koristi_Luku> Destinacija_Koristi_Luku { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plovidba> Plovidbas { get; set; }
    }
}
